
obj-$(CONFIG_CLKDEV_LOOKUP)	+= clkdev.o
obj-$(CONFIG_GENERIC_CLK)	+= clk.o
obj-$(CONFIG_GENERIC_CLK_FIXED)	+= clk-fixed.o
obj-$(CONFIG_GENERIC_CLK_GATE)	+= clk-gate.o
obj-$(CONFIG_GENERIC_CLK_WM831X) += clk-wm831x.o
